---
version: "3.8"

services:
  gollery:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?sslmode=disable

  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - .container_volumes/postgres/data:/var/lib/postgresql/data:rw

volumes:
  pgdata: